version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pokemon-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
